# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /scratch/git_repo/c-class/fpga/c-class/c-class.cache/wt [current_project]
set_property parent.project_path /scratch/git_repo/c-class/fpga/c-class/c-class.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  /scratch/git_repo/c-class/verilog/RegFile.v
  /scratch/git_repo/c-class/verilog/module_decoder_func.v
  /scratch/git_repo/c-class/verilog/mkregisterfile.v
  /scratch/git_repo/c-class/verilog/mkstage2.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /scratch/git_repo/c-class/fpga/c-class/c-class.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /scratch/git_repo/c-class/fpga/c-class/c-class.srcs/constrs_1/new/constraints.xdc]


synth_design -top mkstage2 -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef mkstage2.dcp

catch { report_utilization -file mkstage2_utilization_synth.rpt -pb mkstage2_utilization_synth.pb }
