# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/surya/Desktop/FPU/fpga/mkTbSoc/mkTbSoc.cache/wt [current_project]
set_property parent.project_path /home/surya/Desktop/FPU/fpga/mkTbSoc/mkTbSoc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property include_dirs /home/surya/Desktop/FPU/verilog [current_fileset]
read_verilog -library xil_defaultlib {
  /home/surya/Desktop/FPU/verilog/mkfpu_int_to_dp.v
  /home/surya/Desktop/FPU/verilog/mkfpu_divider64.v
  /home/surya/Desktop/FPU/verilog/mkfpu_sqrt32.v
  /home/surya/Desktop/FPU/verilog/mkfpu_sign_injection32.v
  /home/surya/Desktop/FPU/verilog/mkfpu_fm_add_sub64.v
  /home/surya/Desktop/FPU/verilog/mkfpu_int_to_sp.v
  /home/surya/Desktop/FPU/verilog/mkfpu_fclass64.v
  /home/surya/Desktop/FPU/verilog/mkfpu_convert_dp_sp.v
  /home/surya/Desktop/FPU/verilog/mkfpu_compare_min_max32.v
  /home/surya/Desktop/FPU/verilog/mkfpu_sign_injection64.v
  /home/surya/Desktop/FPU/verilog/mkfpu_sqrt64.v
  /home/surya/Desktop/FPU/verilog/mkfpu_sp_to_int.v
  /home/surya/Desktop/FPU/verilog/mkfpu_dp_to_int.v
  /home/surya/Desktop/FPU/verilog/mkfpu_convert_sp_dp.v
  /home/surya/Desktop/FPU/verilog/mkfpu_fm_add_sub32.v
  /home/surya/Desktop/FPU/verilog/mkfpu_divider32.v
  /home/surya/Desktop/FPU/verilog/mkfpu_fclass32.v
  /home/surya/Desktop/FPU/verilog/mkfpu_compare_min_max64.v
  /home/surya/Desktop/FPU/verilog/mkregisterfile.v
  /home/surya/Desktop/FPU/verilog/mkfpu.v
  /home/surya/Desktop/FPU/verilog/mkprf_new.v
  /home/surya/Desktop/FPU/verilog/module_fn_alu.v
  /home/surya/Desktop/FPU/verilog/mkmuldiv.v
  /home/surya/Desktop/FPU/verilog/module_fn_decode.v
  /home/surya/Desktop/FPU/verilog/mkQuadMem.v
  /home/surya/Desktop/FPU/verilog/mkcsr.v
  /home/surya/Desktop/FPU/verilog/mkdTLB.v
  /home/surya/Desktop/FPU/verilog/mkbranchpredictor.v
  /home/surya/Desktop/FPU/verilog/mkdcache.v
  /home/surya/Desktop/FPU/verilog/mkdecode_opfetch.v
  /home/surya/Desktop/FPU/verilog/mkexecute_stage.v
  /home/surya/Desktop/FPU/verilog/mkiTLB.v
  /home/surya/Desktop/FPU/verilog/mkicache.v
  /home/surya/Desktop/FPU/verilog/mkfetch.v
  /home/surya/Desktop/FPU/verilog/mkmemory_stage.v
  /home/surya/Desktop/FPU/verilog/mkimem.v
  /home/surya/Desktop/FPU/verilog/mkgpio.v
  /home/surya/Desktop/FPU/verilog/mkplicperipheral.v
  /home/surya/Desktop/FPU/verilog/mkclint.v
  /home/surya/Desktop/FPU/verilog/mkriscv.v
  /home/surya/Desktop/FPU/verilog/mkdmem.v
  /home/surya/Desktop/FPU/verilog/mkUart16550.v
  /home/surya/Desktop/FPU/verilog/mkUart_bs.v
  /home/surya/Desktop/FPU/verilog/mkAXI4Lite_AXI4_Bridge.v
  /home/surya/Desktop/FPU/verilog/mkcore_AXI4.v
  /home/surya/Desktop/FPU/verilog/mkslow_peripherals.v
  /home/surya/Desktop/FPU/verilog/mkBootRom.v
  /home/surya/Desktop/FPU/verilog/mkSoc.v
  /home/surya/Desktop/FPU/verilog/module_multiplication.v
  /home/surya/Desktop/FPU/verilog/mkTbSoc.v
  /home/surya/Desktop/FPU/verilog/mkfpu_fm_add_sub_pipe_32.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/surya/Desktop/FPU/src/tcl/constraints.xdc
set_property used_in_implementation false [get_files /home/surya/Desktop/FPU/src/tcl/constraints.xdc]


synth_design -top mkTbSoc -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef mkTbSoc.dcp

catch { report_utilization -file mkTbSoc_utilization_synth.rpt -pb mkTbSoc_utilization_synth.pb }
